version = 0.1

[default.global.parameters]
stack_name      = "policy-tracer-lambda"
region          = "us-east-1"
capabilities    = "CAPABILITY_IAM"
resolve_s3      = true

[default.deploy.parameters]
confirm_changeset = false
fail_on_empty_changeset = false
